name: Build and Run on Azure VM

on:
  workflow_dispatch:

jobs:
  build:
    name: Build on Azure VM
    runs-on: ubuntu-latest
    environment: productenv
    outputs:
      hostname: ${{ vars.HOST }}
      username: ${{ vars.USERNAME }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURESECRET }}" > ~/.ssh/private_key.pem
          chmod 600 ~/.ssh/private_key.pem
      
          
      - name: Build JAR Remotely
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${{ vars.USERNAME }}@${{ vars.HOST }} << 'EOF'
            if [ ! -d ~/secondapplication ]; then
              git clone https://github.com/Murugantk/secondapplication.git ~/secondapplication
            fi
            cd ~/secondapplication
            git pull origin main
            mvn --batch-mode --update-snapshots package
            mkdir -p staging
            cp target/*.jar staging/
            ls -l ~staging/
          EOF


      - name: Cleanup SSH key
        run: rm -f private_key.pem
